# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tapLock_wrappers", use_symbols = TRUE, package_name = "tapLock")

#' @usage NULL
#' @useDynLib tapLock, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

initialize_google_runtime <- function(client_id, client_secret, app_url, use_refresh_token) .Call(wrap__initialize_google_runtime, client_id, client_secret, app_url, use_refresh_token)

initialize_entra_id_runtime <- function(client_id, client_secret, app_url, tenant_id, use_refresh_token) .Call(wrap__initialize_entra_id_runtime, client_id, client_secret, app_url, tenant_id, use_refresh_token)

initialize_keycloak_runtime <- function(client_id, client_secret, app_url, base_url, realm, use_refresh_token) .Call(wrap__initialize_keycloak_runtime, client_id, client_secret, app_url, base_url, realm, use_refresh_token)

#' @title Parse cookies
#' @description Parses cookies from a string
#'
#' @param x A string containing the cookies
#'
#' @return A list containing the cookies
#' @keywords internal
parse_cookies <- function(cookie_string) .Call(wrap__parse_cookies, cookie_string)

AsyncFuture <- new.env(parent = emptyenv())

AsyncFuture$poll <- function() .Call(wrap__AsyncFuture__poll, self)

#' @export
`$.AsyncFuture` <- function (self, name) { func <- AsyncFuture[[name]]; environment(func) <- environment(); func }

#' @export
`[[.AsyncFuture` <- `$.AsyncFuture`

FutureResult <- new.env(parent = emptyenv())

FutureResult$is_error <- function() .Call(wrap__FutureResult__is_error, self)

FutureResult$is_ready <- function() .Call(wrap__FutureResult__is_ready, self)

FutureResult$is_pending <- function() .Call(wrap__FutureResult__is_pending, self)

FutureResult$error <- function() .Call(wrap__FutureResult__error, self)

FutureResult$value <- function() .Call(wrap__FutureResult__value, self)

#' @export
`$.FutureResult` <- function (self, name) { func <- FutureResult[[name]]; environment(func) <- environment(); func }

#' @export
`[[.FutureResult` <- `$.FutureResult`

OAuth2Runtime <- new.env(parent = emptyenv())

OAuth2Runtime$request_token <- function(authorization_code) .Call(wrap__OAuth2Runtime__request_token, self, authorization_code)

OAuth2Runtime$request_token_refresh <- function(refresh_token) .Call(wrap__OAuth2Runtime__request_token_refresh, self, refresh_token)

OAuth2Runtime$decode_token <- function(token) .Call(wrap__OAuth2Runtime__decode_token, self, token)

OAuth2Runtime$get_authorization_url <- function() .Call(wrap__OAuth2Runtime__get_authorization_url, self)

OAuth2Runtime$get_app_url <- function() .Call(wrap__OAuth2Runtime__get_app_url, self)

#' @export
`$.OAuth2Runtime` <- function (self, name) { func <- OAuth2Runtime[[name]]; environment(func) <- environment(); func }

#' @export
`[[.OAuth2Runtime` <- `$.OAuth2Runtime`


# nolint end
